use_default_settings: true

general:
  # Debug mode, only for development. Is overwritten by ${SEARXNG_DEBUG}
  debug: true
  # displayed name
  instance_name: "searxng"
  # For example: https://example.com/privacy
  privacypolicy_url: false
  # use true to use your own donation page written in searx/info/en/donate.md
  # use false to disable the donation link
  donation_url: false
  # mailto:contact@example.com
  contact_url: false
  # record stats
  enable_metrics: true

search:
  autocomplete: "google"
  autocomplete_min: 15
  safe_search: 0
  formats:
    - html
    - json
    - csv

server:
  secret_key: "a2fb23f1b02e6ee83875b09826990de0f6bd908b6638e8c10277d415f6ab852b" # Is overwritten by ${SEARXNG_SECRET}
  limiter: false
  http_protocol_version: "1.0"
  method: "GET"
  default_http_headers:
    X-Content-Type-Options: nosniff
    X-Download-Options: noopen
    X-Robots-Tag: noindex, nofollow
    Referrer-Policy: no-referrer

engines:
  - name: wolframalpha
    disabled: false

categories_as_tabs:
  general:
  images:
  videos:
  news:
  # map:
  # music:
  # it:
  # science:
  files:
  social media:
